#!/usr/bin/python3
from bottle import route, request, run

def check_login(passphrase):
    return True

@route('/')
def login():
    return '''
        <form action="/login" method="post">
            Passphrase: <input name="passphrase" type="password" />
            <input value="Submit" type="submit" />
        </form>
    '''

@route('/login', method='POST')
def do_login():
    passphrase = request.forms.get('passphrase')
    if check_login(passphrase):
        return "<p>Your login information was correct.</p>"
    else:
        return "<p>Login failed.</p>"

run(host='0.0.0.0', port=8080)

